"""Recraft V3 API client for AI image generation.

Calls the Recraft V3 API to generate editorial cover images from text prompts.
Uses the shared httpx client factory for consistent retry/timeout behavior.

Architecture:
    pipeline.py (orchestrator)
    └── recraft.py  <- this module
        └── httpx.Client  <- shared HTTP layer
"""

import logging
import os
from dataclasses import dataclass
from typing import List, Optional

import httpx

from apps.agents.covers.config import (
    IMAGE_HEIGHT,
    IMAGE_WIDTH,
    RECRAFT_API_URL,
    RECRAFT_DEFAULT_MODEL,
    RECRAFT_DEFAULT_STYLE,
    RECRAFT_TIMEOUT,
)
from apps.agents.sources.http import HttpClientConfig, create_http_client

logger = logging.getLogger(__name__)


@dataclass
class GeneratedImage:
    """A single image generated by Recraft V3."""

    image_bytes: bytes
    variation: int
    content_type: str = "image/png"


class RecraftClient:
    """Generates images via the Recraft V3 API.

    Makes one API call per variation. Collects results and logs failures
    individually. Returns whatever succeeded (may be fewer than requested).
    """

    def __init__(
        self,
        api_key: Optional[str] = None,
        http_client: Optional[httpx.Client] = None,
    ) -> None:
        """Initialize with an optional API key and httpx client.

        Args:
            api_key: Recraft API key (falls back to RECRAFT_API_KEY env var).
            http_client: Optional pre-configured httpx client for testing.
        """
        self._api_key = api_key or os.environ.get("RECRAFT_API_KEY", "")
        self._external_client = http_client

    @property
    def is_available(self) -> bool:
        """Check if the Recraft API key is configured."""
        return bool(self._api_key)

    def generate(
        self,
        prompt: str,
        variations: int = 3,
        width: int = IMAGE_WIDTH,
        height: int = IMAGE_HEIGHT,
        style: str = RECRAFT_DEFAULT_STYLE,
    ) -> List[GeneratedImage]:
        """Generate image variations from a text prompt.

        Args:
            prompt: Recraft V3 image prompt.
            variations: Number of images to generate (1-3).
            width: Image width in pixels.
            height: Image height in pixels.
            style: Recraft style preset.

        Returns:
            List of GeneratedImage. May be fewer than requested on partial failure.
            Empty list if API is unavailable or all calls fail.
        """
        if not self.is_available:
            logger.warning("Recraft API key not set")
            return []

        results: List[GeneratedImage] = []

        for i in range(variations):
            image = self._generate_single(prompt, i + 1, width, height, style)
            if image:
                results.append(image)

        return results

    def _generate_single(
        self,
        prompt: str,
        variation: int,
        width: int,
        height: int,
        style: str,
    ) -> Optional[GeneratedImage]:
        """Generate a single image from Recraft V3."""
        client = self._get_client()
        try:
            # Step 1: POST prompt to Recraft API → returns JSON with image URL
            response = client.post(
                RECRAFT_API_URL,
                headers={"Authorization": f"Bearer {self._api_key}"},
                json={
                    "prompt": prompt,
                    "style": style,
                    "model": RECRAFT_DEFAULT_MODEL,
                    "size": f"{width}x{height}",
                },
            )
            response.raise_for_status()

            # Step 2: Extract the generated image URL from response
            data = response.json()
            image_url = data["data"][0]["url"]

            # Step 3: Download the actual image bytes from the URL
            img_response = client.get(image_url)
            img_response.raise_for_status()

            return GeneratedImage(
                image_bytes=img_response.content,
                variation=variation,
            )

        except httpx.TimeoutException:
            logger.warning("Recraft API timeout for variation %d", variation)
            return None
        except httpx.HTTPStatusError as e:
            logger.warning(
                "Recraft API error for variation %d: %d %s",
                variation, e.response.status_code, e.response.text[:200],
            )
            return None
        except (KeyError, IndexError) as e:
            # Recraft returned an unexpected JSON structure
            logger.warning("Unexpected Recraft response format for variation %d: %s", variation, e)
            return None
        except Exception as e:
            logger.warning("Recraft unexpected error for variation %d: %s", variation, e)
            return None
        finally:
            if not self._external_client:
                client.close()

    def _get_client(self) -> httpx.Client:
        """Get or create an httpx client."""
        if self._external_client:
            return self._external_client
        return create_http_client(HttpClientConfig(timeout=RECRAFT_TIMEOUT))
