"""CLI entry point for the FUNDING agent.

Usage:
    python -m apps.agents.funding.main [--week N] [--output PATH] [--dry-run] [--persist]
    python -m apps.agents.funding.main --week 7 --persist
"""

import argparse
import logging
import os
import sys
from datetime import datetime, timezone
from uuid import uuid4

# Add project root to path
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "..")))

from apps.agents.funding.agent import FundingAgent


def setup_logging(verbose: bool = False) -> None:
    """Configure structured logging.

    Args:
        verbose: Enable debug-level logging
    """
    level = logging.DEBUG if verbose else logging.INFO
    logging.basicConfig(
        level=level,
        format="%(asctime)s [%(name)s] %(levelname)s: %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
    )


def persist_to_db(agent: FundingAgent, result, metadata) -> None:
    """Save agent run and funding rounds to the database.

    Args:
        agent: FundingAgent instance
        result: AgentOutput from agent.run()
        metadata: Run metadata from agent.get_run_metadata()
    """
    from dotenv import load_dotenv
    from sqlalchemy import create_engine
    from sqlalchemy.orm import sessionmaker

    from apps.agents.funding.db_writer import persist_all_events
    from packages.database.models.agent_run import AgentRun
    from packages.database.models.content_piece import ContentPiece

    load_dotenv()
    db_url = os.getenv("DATABASE_URL", "postgresql://sinal:sinal_dev@localhost:5432/sinal_dev")
    engine = create_engine(db_url)
    Session = sessionmaker(bind=engine)
    session = Session()

    try:
        now = datetime.now(timezone.utc)

        # Create AgentRun record
        agent_run = AgentRun(
            id=uuid4(),
            agent_name=agent.agent_name,
            run_id=agent.run_id,
            started_at=metadata.get("started_at", now),
            completed_at=now,
            status="completed",
            items_collected=metadata.get("items_collected", 0),
            items_processed=metadata.get("items_processed", 0),
            items_output=metadata.get("items_processed", 0),  # All processed events are output
            avg_confidence=(
                result.confidence.composite if hasattr(result.confidence, "composite") else None
            ),
            data_sources={"sources": agent.provenance.get_sources()},
            error_count=0,
        )
        session.add(agent_run)

        # Persist funding rounds
        scored_events = getattr(agent, "_scored_events", [])
        if scored_events:
            events_with_confidence = [
                (scored.event, scored.confidence.composite) for scored in scored_events
            ]
            stats = persist_all_events(session, events_with_confidence)
            logging.getLogger("funding.main").info(
                "Persisted funding rounds: %s", stats
            )

        # Create ContentPiece for the report
        slug = f"funding-semanal-{agent.week_number}"
        existing = session.query(ContentPiece).filter_by(slug=slug).first()

        if existing:
            existing.body_md = result.body_md
            existing.confidence_dq = result.confidence.dq_display
            existing.confidence_ac = result.confidence.ac_display
            existing.sources = result.sources
            existing.summary = result.summary
            existing.review_status = "pending_review"
            existing.agent_run_id = agent.run_id
        else:
            content = ContentPiece(
                id=uuid4(),
                title=result.title,
                slug=slug,
                body_md=result.body_md,
                body_html="",  # Will be generated by editorial pipeline
                summary=result.summary,
                content_type=result.content_type,
                agent_name=agent.agent_name,
                agent_run_id=agent.run_id,
                sources=result.sources,
                confidence_dq=result.confidence.dq_display,
                confidence_ac=result.confidence.ac_display,
                review_status="pending_review",
            )
            session.add(content)

        session.commit()
        logging.getLogger("funding.main").info("Persisted run %s to database", agent.run_id)

    except Exception as e:
        session.rollback()
        logging.getLogger("funding.main").error("Failed to persist to database: %s", e)
        raise
    finally:
        session.close()


def main() -> None:
    """Main entry point for FUNDING agent CLI."""
    parser = argparse.ArgumentParser(
        description="FUNDING — Sinal.lab Investment Tracking Agent"
    )
    parser.add_argument(
        "--week",
        type=int,
        default=1,
        help="Week number of the year (default: 1)",
    )
    parser.add_argument(
        "--output",
        type=str,
        default=None,
        help="Path to save the report Markdown output",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Run without saving output or persisting to database",
    )
    parser.add_argument(
        "--persist",
        action="store_true",
        help="Save agent run and funding rounds to the database",
    )
    parser.add_argument(
        "--verbose",
        "-v",
        action="store_true",
        help="Enable verbose logging",
    )

    args = parser.parse_args()
    setup_logging(args.verbose)

    logger = logging.getLogger("funding.main")
    logger.info("Starting FUNDING agent, week #%d", args.week)

    # Run the agent
    agent = FundingAgent(week_number=args.week)
    result = agent.run()

    # Validate output
    errors = result.validate()
    if errors:
        logger.warning("Output validation issues: %s", errors)

    # Display results
    metadata = agent.get_run_metadata()
    logger.info("Run metadata: %s", metadata)
    logger.info("Confidence: %s", result.confidence.to_dict())
    logger.info("Provenance summary: %s", agent.provenance.summary())

    if args.dry_run:
        logger.info("Dry run — not saving output")
        print("\n" + "=" * 60)
        print(result.to_markdown()[:2000])
        print("..." if len(result.to_markdown()) > 2000 else "")
        print("=" * 60)
        return

    # Save Markdown output
    md_content = result.to_markdown()
    if args.output:
        output_path = args.output
    else:
        os.makedirs("apps/agents/funding/output", exist_ok=True)
        output_path = f"apps/agents/funding/output/funding-week-{args.week}.md"

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(md_content)
    logger.info("Markdown saved to %s", output_path)

    # Persist to database
    if args.persist:
        logger.info("Persisting to database...")
        persist_to_db(agent, result, metadata)

    print(f"\nFUNDING Report Week #{args.week} generated successfully!")
    print(f"  Events collected: {metadata['items_collected']}")
    print(f"  Events processed: {metadata['items_processed']}")
    print(f"  Sources: {agent.provenance.summary()['unique_sources']}")
    print(f"  Confidence: {result.confidence.grade} (DQ: {result.confidence.dq_display:.1f}/5, AC: {result.confidence.ac_display:.1f}/5)")
    print(f"  Output: {output_path}")
    if args.persist:
        print("  DB: persisted")


if __name__ == "__main__":
    main()
