"""Generate cover images for newsletters and update the database.

Usage:
    python3 scripts/generate_covers.py                        # all without covers
    python3 scripts/generate_covers.py --limit 10             # only 10
    python3 scripts/generate_covers.py --dry-run              # preview without generating
    python3 scripts/generate_covers.py --database-url "..."   # custom DB (e.g. production)
    python3 scripts/generate_covers.py --sync-only "..."      # sync images to another DB
"""

import argparse
import json
import logging
import os
import sys
import time
from pathlib import Path

_PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(_PROJECT_ROOT))

from dotenv import load_dotenv  # noqa: E402

load_dotenv(_PROJECT_ROOT / ".env")

import psycopg2  # noqa: E402

from apps.agents.covers.pipeline import CoverPipeline  # noqa: E402
from apps.agents.covers.prompt_generator import CoverBriefing  # noqa: E402

logger = logging.getLogger(__name__)


def get_newsletters_without_covers(conn, limit: int = 200):
    """Fetch published newsletters that don't have a hero_image yet."""
    cur = conn.cursor()
    cur.execute(
        """
        SELECT id, title, subtitle, slug, agent_name, metadata::text,
               published_at, body_md
        FROM content_pieces
        WHERE review_status = 'published'
          AND (
            metadata IS NULL
            OR metadata->>'hero_image' IS NULL
          )
        ORDER BY published_at DESC
        LIMIT %s
        """,
        (limit,),
    )
    rows = cur.fetchall()
    cur.close()

    newsletters = []
    for row in rows:
        meta = json.loads(row[5]) if row[5] else {}
        lede = row[2] or ""
        if not lede and row[7]:
            for line in row[7].split("\n"):
                stripped = line.strip()
                if (
                    stripped
                    and not stripped.startswith("#")
                    and not stripped.startswith("---")
                    and not stripped.startswith("*")
                    and not stripped.startswith(">")
                    and len(stripped) > 30
                ):
                    lede = stripped[:200]
                    break
        if not lede:
            lede = row[1]

        agent = row[4] or "sintese"  # fallback for NULL agent_name
        edition = meta.get("edition_number", 30)
        newsletters.append({
            "id": row[0],
            "title": row[1],
            "lede": lede,
            "slug": row[3],
            "agent": agent,
            "metadata": meta,
            "edition": edition,
        })
    return newsletters


def get_newsletters_with_covers(conn):
    """Fetch all newsletters that already have a hero_image (for sync)."""
    cur = conn.cursor()
    cur.execute(
        """
        SELECT slug, metadata::text
        FROM content_pieces
        WHERE review_status = 'published'
          AND metadata->>'hero_image' IS NOT NULL
        """
    )
    rows = cur.fetchall()
    cur.close()

    covers = {}
    for row in rows:
        meta = json.loads(row[1]) if row[1] else {}
        hero = meta.get("hero_image")
        if hero and hero.get("url"):
            covers[row[0]] = hero
    return covers


def update_hero_image(conn, content_id: str, image_url: str, agent: str):
    """Update metadata_.hero_image for a content piece."""
    cur = conn.cursor()
    cur.execute("SELECT metadata::text FROM content_pieces WHERE id = %s", (content_id,))
    row = cur.fetchone()
    meta = json.loads(row[0]) if row and row[0] else {}

    meta["hero_image"] = {
        "url": image_url,
        "alt": f"Cover image for {agent.upper()} newsletter",
        "caption": f"Generated by Sinal AI — {agent.upper()} agent",
        "credit": "Sinal / Recraft V3",
    }

    cur.execute(
        "UPDATE content_pieces SET metadata = %s::jsonb WHERE id = %s",
        (json.dumps(meta), content_id),
    )
    conn.commit()
    cur.close()


def sync_covers_to_db(source_db_url: str, target_db_url: str):
    """Copy hero_image metadata from source DB to target DB (matched by slug)."""
    print("Syncing covers from source to target database...\n")

    source_conn = psycopg2.connect(source_db_url)
    target_conn = psycopg2.connect(target_db_url)

    covers = get_newsletters_with_covers(source_conn)
    print(f"Found {len(covers)} newsletters with covers in source DB.\n")

    synced = 0
    for slug, hero_image in covers.items():
        cur = target_conn.cursor()
        cur.execute(
            "SELECT id, metadata::text FROM content_pieces WHERE slug = %s",
            (slug,),
        )
        row = cur.fetchone()
        if not row:
            cur.close()
            continue

        meta = json.loads(row[1]) if row[1] else {}
        if meta.get("hero_image", {}).get("url") == hero_image["url"]:
            cur.close()
            continue  # already synced

        meta["hero_image"] = hero_image
        cur.execute(
            "UPDATE content_pieces SET metadata = %s::jsonb WHERE id = %s",
            (json.dumps(meta), row[0]),
        )
        target_conn.commit()
        cur.close()
        synced += 1
        print(f"  Synced: {slug}")

    source_conn.close()
    target_conn.close()
    print(f"\nDone — {synced} newsletters updated in target DB.")


def main():
    parser = argparse.ArgumentParser(description="Generate covers for newsletters")
    parser.add_argument("--limit", type=int, default=200, help="Max newsletters to process")
    parser.add_argument("--dry-run", action="store_true", help="Preview without generating")
    parser.add_argument("--verbose", action="store_true", help="Verbose logging")
    parser.add_argument("--database-url", type=str, default=None, help="Custom database URL")
    parser.add_argument(
        "--sync-to", type=str, default=None,
        help="Sync existing covers from local DB to this target DB URL",
    )
    args = parser.parse_args()

    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(asctime)s %(levelname)s %(message)s",
    )

    db_url = args.database_url or os.environ.get("DATABASE_URL")
    if not db_url:
        print("ERROR: DATABASE_URL not set", file=sys.stderr)
        sys.exit(1)

    # Sync mode: copy hero_image from local DB to target DB
    if args.sync_to:
        sync_covers_to_db(source_db_url=db_url, target_db_url=args.sync_to)
        return

    conn = psycopg2.connect(db_url)
    newsletters = get_newsletters_without_covers(conn, limit=args.limit)

    if not newsletters:
        print("\nAll newsletters already have cover images!")
        conn.close()
        return

    est_time = len(newsletters) * 15  # ~15s per cover
    est_cost = len(newsletters) * 0.04  # ~$0.04 per Recraft image
    print(f"\nFound {len(newsletters)} newsletters without covers.")
    print(f"Estimated: ~{est_time // 60}min, ~US${est_cost:.2f} in Recraft API\n")

    for nl in newsletters:
        has_cover = "hero_image" in nl["metadata"]
        marker = "  " if not has_cover else "SKIP"
        print(f"  {marker} [{nl['agent']:10s}] {nl['title'][:65]}")

    if args.dry_run:
        print("\nDRY RUN — no images generated.")
        conn.close()
        return

    pipeline = CoverPipeline()
    results = []
    failures = []
    start_time = time.time()

    for i, nl in enumerate(newsletters, 1):
        print(f"\n[{i}/{len(newsletters)}] {nl['agent'].upper()} — {nl['title'][:70]}")

        briefing = CoverBriefing(
            headline=nl["title"],
            lede=nl["lede"],
            agent=nl["agent"],
            edition=nl["edition"],
        )

        result = pipeline.run(briefing, variations=1)

        if result.errors:
            for err in result.errors:
                print(f"  WARNING: {err}")

        if result.images:
            url = result.images[0]["url"]
            update_hero_image(conn, nl["id"], url, nl["agent"])
            print(f"  OK: {url}")
            results.append({"slug": nl["slug"], "agent": nl["agent"], "url": url})
        else:
            print(f"  FAILED")
            failures.append(nl["slug"])

    conn.close()
    elapsed = time.time() - start_time

    print(f"\n{'='*60}")
    print(f"DONE — {len(results)}/{len(newsletters)} covers generated in {elapsed:.0f}s")
    if failures:
        print(f"FAILED ({len(failures)}): {', '.join(failures)}")
    print()


if __name__ == "__main__":
    main()
