#!/usr/bin/env python3
"""Replace old social_signals data with fresh VOZES + PULSO pipeline output.

Steps:
    1. Delete all signal_clusters, social_signals, and weekly_pulses
       generated by the old social_signals agent
    2. Run VOZES (collect + classify + persist individual signals)
    3. Run PULSO (cluster + score + persist clusters and weekly pulse)

Usage:
    # Dry-run: show what would be deleted, then run pipeline without persist
    python scripts/refresh_social_signals.py --dry-run

    # Full run: delete old data, run pipeline, persist new data
    python scripts/refresh_social_signals.py

    # Specify week (defaults to current ISO week)
    python scripts/refresh_social_signals.py --week 16

    # Skip deletion (only run pipeline, keep old data)
    python scripts/refresh_social_signals.py --skip-cleanup
"""

import argparse
import logging
import sys
from datetime import datetime
from pathlib import Path

from dotenv import load_dotenv

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))
load_dotenv(PROJECT_ROOT / ".env")

from packages.database.session import get_session
from packages.database.models.signal_cluster import SignalCluster
from packages.database.models.social_signal import SocialSignal
from packages.database.models.weekly_pulse import WeeklyPulse

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [refresh] %(levelname)s: %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
logger = logging.getLogger("refresh")


def cleanup_old_data(session, dry_run: bool = False) -> dict:
    """Delete all data generated by the old social_signals agent.

    Returns counts of deleted records.
    """
    stats = {}

    # Count records to delete
    clusters = session.query(SignalCluster).filter(
        SignalCluster.agent_run_id.like("social_signals%")
    ).count()

    signals = session.query(SocialSignal).filter(
        SocialSignal.agent_run_id.like("social_signals%")
    ).count()

    pulses = session.query(WeeklyPulse).filter(
        WeeklyPulse.agent_run_id.like("social_signals%")
    ).count()

    stats = {
        "clusters": clusters,
        "signals": signals,
        "pulses": pulses,
    }

    logger.info(
        "Old social_signals data: %d clusters, %d signals, %d pulses",
        clusters, signals, pulses,
    )

    if dry_run:
        logger.info("DRY RUN: would delete %d total records", sum(stats.values()))
        return stats

    # Delete in order (signals reference clusters via cluster_id)
    if signals > 0:
        session.query(SocialSignal).filter(
            SocialSignal.agent_run_id.like("social_signals%")
        ).delete(synchronize_session="fetch")
        logger.info("Deleted %d social signals", signals)

    if clusters > 0:
        session.query(SignalCluster).filter(
            SignalCluster.agent_run_id.like("social_signals%")
        ).delete(synchronize_session="fetch")
        logger.info("Deleted %d signal clusters", clusters)

    if pulses > 0:
        session.query(WeeklyPulse).filter(
            WeeklyPulse.agent_run_id.like("social_signals%")
        ).delete(synchronize_session="fetch")
        logger.info("Deleted %d weekly pulses", pulses)

    session.commit()
    logger.info("Cleanup committed")
    return stats


def run_pipeline(week: int, dry_run: bool = False) -> int:
    """Run VOZES -> PULSO pipeline.

    Returns 0 on success, 1 on failure.
    """
    from scripts.run_agents import orchestrate_vozes_pulso

    session = get_session()
    try:
        if dry_run:
            # In dry-run, run VOZES only (no persist) to check collection quality
            from scripts.run_agents import orchestrate_single_agent

            logger.info("DRY RUN: running VOZES only (no persist)")
            code = orchestrate_single_agent(
                "vozes",
                period_value=week,
                session=session,
                enable_editorial=False,
                enable_evidence=False,
            )
            return code

        code = orchestrate_vozes_pulso(
            week_value=week,
            session=session,
            enable_editorial=False,
            enable_evidence=False,
        )
        return code
    finally:
        session.close()


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Replace old social_signals data with VOZES + PULSO pipeline",
    )
    parser.add_argument(
        "--week", type=int, default=None,
        help="Week number (defaults to current ISO week)",
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Show what would be deleted and run pipeline without persisting",
    )
    parser.add_argument(
        "--skip-cleanup", action="store_true",
        help="Skip deletion of old data (only run pipeline)",
    )
    parser.add_argument(
        "--verbose", "-v", action="store_true",
        help="Verbose logging",
    )
    args = parser.parse_args()

    if args.verbose:
        logging.getLogger().setLevel(logging.DEBUG)

    week = args.week or datetime.now().isocalendar()[1]
    logger.info("Target week: %d", week)

    # Step 1: Cleanup
    if not args.skip_cleanup:
        logger.info("=" * 50)
        logger.info("Step 1/2: Cleaning up old social_signals data")
        session = get_session()
        try:
            cleanup_old_data(session, dry_run=args.dry_run)
        finally:
            session.close()
    else:
        logger.info("Skipping cleanup (--skip-cleanup)")

    # Step 2: Run pipeline
    logger.info("=" * 50)
    logger.info("Step 2/2: Running VOZES -> PULSO pipeline")
    code = run_pipeline(week, dry_run=args.dry_run)

    if code == 0:
        logger.info("=" * 50)
        logger.info("Refresh complete. New data is live.")
    else:
        logger.error("Pipeline failed with code %d", code)
        sys.exit(1)


if __name__ == "__main__":
    main()
