/**
 * Tests for the Artigos listing page and ArticleContent detail component.
 *
 * Covers: cover image rendering on cards, hero image on detail page,
 * fallback gradient when no cover, author display, and badge rendering.
 */
import { describe, it, expect, vi, beforeEach } from "vitest";
import { render, screen } from "@testing-library/react";
import React from "react";

import ArticleContent from "@/components/article/ArticleContent";
import type { ContentApiItem } from "@/lib/newsletter";

// ---------------------------------------------------------------------------
// Mocks
// ---------------------------------------------------------------------------

vi.mock("next-auth/react", () => ({
  useSession: () => ({ status: "authenticated", data: { user: {} } }),
}));

vi.mock("next/link", () => ({
  default: ({ children, href, ...rest }: { children: React.ReactNode; href: string }) =>
    React.createElement("a", { href, ...rest }, children),
}));

// ---------------------------------------------------------------------------
// Fixtures
// ---------------------------------------------------------------------------

function makeArticle(overrides: Partial<ContentApiItem> = {}): ContentApiItem {
  return {
    id: "uuid-1",
    title: "6 PRs para colocar um site no ar",
    slug: "6-prs-para-colocar-um-site-no-ar",
    content_type: "ARTICLE",
    review_status: "published",
    published_at: "2026-02-21T12:00:00Z",
    subtitle: "Semana 1 do diario de construcao",
    author_name: "Santos de Machine",
    body_md: "# Heading\n\nParagraph one about building.\n\nParagraph two about deploy.",
    metadata_: null,
    ...overrides,
  };
}

const HERO_IMAGE = {
  url: "https://blob.vercel-storage.com/covers/artigos/test.png",
  alt: "Cover image for ARTIGO",
  caption: "Generated by Sinal AI",
  credit: "Sinal / Recraft V3",
};

// ---------------------------------------------------------------------------
// ArticleContent — hero image rendering
// ---------------------------------------------------------------------------

describe("ArticleContent — hero image", () => {
  it("renders hero image when metadata_ has hero_image", () => {
    const item = makeArticle({ metadata_: { hero_image: HERO_IMAGE } });
    render(<ArticleContent item={item} />);

    const img = screen.getByRole("img");
    expect(img).toHaveAttribute("src", HERO_IMAGE.url);
  });

  it("renders caption and credit when provided", () => {
    const item = makeArticle({ metadata_: { hero_image: HERO_IMAGE } });
    render(<ArticleContent item={item} />);

    expect(screen.getByText("Generated by Sinal AI")).toBeInTheDocument();
    expect(screen.getByText("Sinal / Recraft V3")).toBeInTheDocument();
  });

  it("does not render img when metadata_ is null", () => {
    const item = makeArticle({ metadata_: null });
    render(<ArticleContent item={item} />);

    expect(screen.queryByRole("img")).not.toBeInTheDocument();
  });

  it("does not render img when hero_image is null", () => {
    const item = makeArticle({ metadata_: { hero_image: null } });
    render(<ArticleContent item={item} />);

    expect(screen.queryByRole("img")).not.toBeInTheDocument();
  });
});

// ---------------------------------------------------------------------------
// ArticleContent — article header
// ---------------------------------------------------------------------------

describe("ArticleContent — header", () => {
  it("renders article title", () => {
    const item = makeArticle();
    render(<ArticleContent item={item} />);

    expect(screen.getByRole("heading", { level: 1 })).toHaveTextContent(
      "6 PRs para colocar um site no ar",
    );
  });

  it("renders ARTIGO badge", () => {
    const item = makeArticle();
    render(<ArticleContent item={item} />);

    expect(screen.getByText("Artigo")).toBeInTheDocument();
  });

  it("renders author name when provided", () => {
    const item = makeArticle({ author_name: "Fabiano Cruz" });
    render(<ArticleContent item={item} />);

    expect(screen.getByText("Fabiano Cruz")).toBeInTheDocument();
    expect(screen.getByText("Autor")).toBeInTheDocument();
  });

  it("renders Sinal Editorial when author_name is null", () => {
    const item = makeArticle({ author_name: null });
    render(<ArticleContent item={item} />);

    expect(screen.getByText("Sinal Editorial")).toBeInTheDocument();
    expect(screen.getByText("Redacao")).toBeInTheDocument();
  });

  it("renders subtitle when provided", () => {
    const item = makeArticle({ subtitle: "Semana 1 do diario de construcao" });
    render(<ArticleContent item={item} />);

    expect(screen.getByText("Semana 1 do diario de construcao")).toBeInTheDocument();
  });

  it("renders formatted date", () => {
    const item = makeArticle({ published_at: "2026-02-21T12:00:00Z" });
    render(<ArticleContent item={item} />);

    // Date should be formatted in pt-BR
    expect(screen.getByText(/21 de fevereiro de 2026/)).toBeInTheDocument();
  });
});

// ---------------------------------------------------------------------------
// ArticleContent — navigation
// ---------------------------------------------------------------------------

describe("ArticleContent — navigation", () => {
  it("renders back to artigos link", () => {
    const item = makeArticle();
    render(<ArticleContent item={item} />);

    const backLinks = screen.getAllByRole("link", {
      name: /Voltar aos Artigos|Ver todos os artigos/,
    });
    expect(backLinks.length).toBeGreaterThanOrEqual(1);
    expect(backLinks[0]).toHaveAttribute("href", "/artigos");
  });
});

// ---------------------------------------------------------------------------
// ArticleContent — body content
// ---------------------------------------------------------------------------

describe("ArticleContent — body", () => {
  it("renders markdown body content", () => {
    const item = makeArticle({ body_md: "# Heading\n\nSome article content here." });
    render(<ArticleContent item={item} />);

    expect(screen.getByText("Some article content here.")).toBeInTheDocument();
  });

  it("handles empty body gracefully", () => {
    const item = makeArticle({ body_md: "" });
    render(<ArticleContent item={item} />);

    // Should not crash
    expect(screen.getByRole("heading", { level: 1 })).toBeInTheDocument();
  });
});
